flowchart TB
    subgraph Front-End
    direction TB
        A1((Cat-M1)) -->|MQTT| A2(RabbitMQ <br> <i> mq </i>) --> A3[MQTT Pollers <br> <i> mqtt]
        B1((TTN)) --> |https| B2[TTN Webhook <br> <i> ttn_webhook] --> B3{{ttn_exchange}} --> C4[TTN Decoder <br> <i>ttn_decoder]
        C1((REST APIs)) --> |https| C2[REST API Pollers <br> <i> pollers] 
       style A3 stroke-dasharray: 5 5
    end
    subgraph Mid-Tier
        D1{{physical_timeseries}} --> D2[Device Mapper <br> <i>lm] --> D3{{logical_timeseries}}
        A3 --> D1
        C2 --> D1
        C4 --> D1
    end
    subgraph Back-End 
        E1[Other destination <br> <i> ?]
        F1[Ubidots Writer <br> <i> delivery]
        
        D3 -->E1
        D3 --> F1
        
    end
    
Z[(Postreg <br> <i> db </i>)]
X[Mgmt App <br> <i> webapp]
Y[REST API <br> <i> restapi]
X --> Y
Front-End o--o Z
Mid-Tier o--o Z

Y o--o Z


   